services:
  db:
    image: postgres:17
    container_name: computer_club_db
    hostname: computer_club_db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
